version: '3.9'

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-pern_demo}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - carental
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  migrate:
    image: ghcr.io/zonprox/carental-server:latest
    depends_on:
      db:
        condition: service_healthy
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://postgres:${POSTGRES_PASSWORD:-postgres}@db:5432/${POSTGRES_DB:-pern_demo}?schema=public
      JWT_SECRET: ${JWT_SECRET}
      APP_URL: ${APP_URL}
      SERVER_PORT: 4000
      CLIENT_PORT: 5173
    command: >
      sh -c "
      npm --prefix server run prisma:generate &&
      npm --prefix server run migrate &&
      node server/scripts/ensure-setup-flag.js
      "
    networks:
      - carental
    restart: "no"

  server:
    image: ghcr.io/zonprox/carental-server:latest
    depends_on:
      db:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://postgres:${POSTGRES_PASSWORD:-postgres}@db:5432/${POSTGRES_DB:-pern_demo}?schema=public
      JWT_SECRET: ${JWT_SECRET}
      APP_URL: ${APP_URL}
      SERVER_PORT: 4000
      CLIENT_PORT: 5173
    ports:
      - "${SERVER_PORT:-4000}:4000"
    networks:
      - carental
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:4000/api/health"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: unless-stopped

  client:
    image: ghcr.io/zonprox/carental-client:latest
    depends_on:
      - server
    ports:
      - "${CLIENT_PORT:-5173}:80"
    networks:
      - carental
    restart: unless-stopped

volumes:
  pgdata:

networks:
  carental:
    driver: bridge
